name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull project
      uses: actions/checkout@v3
      with:
          submodules: 'recursive'
        
    - name: Install packages
      run: sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python-is-python3
        
    - name: Download SDK
      run : git clone --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
        
    - name: Restore Cache
      uses: actions/cache/restore@v3
      with:
        path: build/
        key: ${{ runner.os }}-build-output
        
    - name: Build
      run: |
        ./ESP8266_RTOS_SDK/install.sh
        . ./ESP8266_RTOS_SDK/export.sh
        make
        
    - name: Save Cache
      uses: actions/cache/save@v3
      with:
        path: build/
        key: ${{ runner.os }}-build-output
  
    - name: Download firmware
      uses: actions/upload-artifact@v3
      with:
        name: Template
        path: |
          build/bootloader/bootloader.*
          build/partitions_singleapp.*
          build/template.*
