name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull project
      uses: actions/checkout@v3
      with:
          submodules: 'recursive'
          
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-serial
        python -m pip install --user -r ./ESP8266_RTOS_SDK/requirements.txt
        git clone https://github.com/espressif/ESP8266_RTOS_SDK.git
        wget https://dl.espressif.com/dl/xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
        tar -xzf xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
        ./ESP8266_RTOS_SDK/install.sh
        . ./ESP8266_RTOS_SDK/export.sh
        make
        
    - name: Download firmware
      uses: actions/upload-artifact@v3
      with:
        name: Template
        path: build/
